apiVersion: v1
kind: Secret
metadata:
  name: git-credentials
type: kubernetes.io/basic-auth
stringData:
  username: <your-GitHub-user-name>
  password: <your-GitHub-personal-access-token-with-repo-scope>